##### database connection info
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mariadb://systudy.com:3306/jpashop?useUnicode=true&characterEncoding=utf-8
    username: sy.cha
    password: asdfasdf
    driver-class-name: org.mariadb.jdbc.Driver
  output:
    ansi:
      enabled: always


  ###### jpa
  jpa:
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      #ddl-auto: create # 애플리케이션 실행 시점에 테이블 drop후 다시 생성
      ddl-auto: none
    properties:
      hibernate:
        #       show_sql: true   # 시스템 아웃에 출력
        format_sql: true
        default_batch_fetch_size: 100 # fetch join 컬렉션 성능 최적화 설정. 루프를 돌면서 미리떙겨와서  in 쿼리 처리
        # n+1 문제에서 해방됨??...
####### log
logging:
  level:
    org.hibernate.SQL: debug  # 로거에 출력
    #org.hibernate.type: trace